baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Boise Trans Collective'
theme = 'hugo-universal-theme'
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[params.topbar]
    enable = true

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Instagram"
    url = "https://www.instagram.com/transboise/"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/BoiseTransCollective/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/transboise"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:boisetranscollective@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 5
    name = "Discord"
    url = "https://discord.gg/gvbrMdhKXu"
    pre = "<i class='fas fa-2x fa-brands fa-discord'></i>"

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Event Calendar"
    identifier = "menu.calendar"
    url        = "/calendar/"
    weight     = 2

[[menu.main]]
    name    = "About"
    identifier  = "menu.about"
    url     = "/about/"
    weight = 3

[[menu.main]]
    name    = "Resources"
    identifier  = "menu.resources"
    url     = "/resources/"
    weight = 4

[[menu.main]]
    name    = "Donate"
    identifier  = "menu.donate"
    url     = "/donate/"
    weight = 5


# banner
[params.carouselHomepage]
    enable = true

# about banner
[params.testimonials]
    enable = true
    title = "We work with musicians, artists, and those of all talents to create environments where you can express yourself freely, safely, and most of all: LOUDLY & PROUDLY!"


[params]

    defaultDescription = "Site template made by Devcows using Hugo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "pink"

    copyright = "Copyright (c) 2024, Boise Trans Collective; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = true
    logo_text = "Boise Trans Collective"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
